# Generated by Django 4.0.1 on 2022-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchange',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
